1 Week Preparation Kit: Day 5
jdalbosco/hackerrank pull request #7
Opened 2022-06-18 04:11 UTC by jdalbosco

2022-06-18 05:13 UTC, camargodev requested changes

2022-06-18 05:13 UTC, camargodev commented on preparation-kits/one-week/d5-balanced_brackets.py
> +    if opening == '[': return True if closing == ']' else False
```suggestion
    return opening+closing in ['()', '[]', '{}']
```

2022-06-18 05:13 UTC, camargodev commented on preparation-kits/one-week/d5-mock_test.py
> +        if number - diff in numbers_set:
```suggestion
        if (number - diff) in numbers_set:
```

2022-06-18 06:45 UTC, jdalbosco commented on preparation-kits/one-week/d5-balanced_brackets.py
> +    if opening == '[': return True if closing == ']' else False
_chef's kiss_

2022-06-18 07:06 UTC, camargodev approved these changes

2022-06-20 13:25 UTC, jdalbosco commented on preparation-kits/one-week/d5-merge_two_sorted_linked_lists.py
> +def mergeLists(head_A, head_B):
```suggestion
def merge_lists(head_A, head_B):
```

2022-06-20 13:30 UTC, merged